feat: sync polaris-controller to polaris server.
polarismesh/polaris-controller pull request #109
Opened 2022-11-30 09:12 UTC by lhiamgeek

**Please provide issue(s) of this PR:**
Fixes #108 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Docs
- [ ] Inject Sidecar
- [ ] Installation
- [X] Performance and Scalability
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [X] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-11-30 09:39 UTC, chuntaojun commented on pkg/util/helper.go
> +var controllerNamespace = "polaris-system"
var (
   ignoreSyncService = map[string]struct{}{
      "service": {}
   }
)

2022-11-30 09:39 UTC, chuntaojun commented on pkg/util/helper.go
> +	if svc.Namespace == controllerNamespace && svc.Name == controllerServiceName {
这里直接根据上面的 map 来做判断处理

2022-12-01 04:26 UTC, chuntaojun requested changes

2022-12-01 04:26 UTC, chuntaojun commented on pkg/controller/controller.go
> +		_, err := p.provider.Register(req)
可以更新了 polaris-go 的版本，用 RegisterInstance

2022-12-01 04:26 UTC, chuntaojun commented on pkg/controller/controller.go
> +	p.registerController(endpoint)
挪到 controller 启动的时候处理吧，POD_IP 是可以通过注入到 ENV 拿到的

2022-12-07 04:27 UTC, chuntaojun requested changes

2022-12-07 04:27 UTC, chuntaojun commented on cmd/polaris-controller/app/polaris-controller-manager.go
> +func buildAPI() (consumerAPI api.ConsumerAPI, providerAPI api.ProviderAPI, err error) {
不建议返回值带上名称，这里调整下吧

2022-12-07 04:32 UTC, lhiamgeek commented on cmd/polaris-controller/app/polaris-controller-manager.go
> +func buildAPI() (consumerAPI api.ConsumerAPI, providerAPI api.ProviderAPI, err error) {
ok

2022-12-07 06:47 UTC, chuntaojun commented on cmd/polaris-controller/app/polaris-controller-manager.go
> +	req.ServiceToken = globalToken
这里不是用 globalToken，这里是北极星 用户/用户组 token

2022-12-07 06:47 UTC, chuntaojun commented on cmd/polaris-controller/app/polaris-controller-manager.go
> +	globalToken                     = "polaris@12345678"
remove it

2022-12-07 06:48 UTC, chuntaojun commented on cmd/polaris-controller/app/polaris-controller-manager.go
> +	req.ServiceToken = globalToken
serviceSync:
      mode: "all"
      serverAddress: #POLARIS_HOST#
      # 北极星开启鉴权时需要配置
      accessToken: #POLARIS_TOKEN#

2022-12-08 03:48 UTC, chuntaojun approved these changes

2022-12-08 03:48 UTC, merged